
slides:
    -
        text: 1
        data:
            x: 0
            z: 0
            "rotate-y": 0
    -
        text: 2
        data:
            x: 100
            z: -100
            "rotate-y": 90
    -
        text: 3
        data:
            x: 0
            z: -200
            "rotate-y": 180
    -
        text: 4
        data:
            x: -100
            z: -100
            "rotate-y": 270
    -
        text: 5
        data:
            x: 0
            y: -100
            z: -100
            "rotate-y": 360
            "rotate-x": 90
    -
        text: 6
        data:
            x: 0
            y: 100
            z: -100
            "rotate-y": 360
            "rotate-x": -90

config:
    inactive_opacity: 1
    data:
        transition-duration: 1000
        min-scale: 1
    attr:
        style: "width: 100%;height: 100%;"
