parameters:
    easy_impress_layout: 'EasyImpressBundle::layout.html.twig'

services:
    easy_impress.controller.presentation:
        class: Orbitale\Bundle\EasyImpressBundle\Controller\PresentationController
        arguments:
            - '%easy_impress_layout%'
            - '@impress'
            - '@templating'
